services:
  - type: web
    name: internship-tracker-backend
    env: python
    buildCommand: "python -m pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: internship-tracker-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: True
    plan: free
